export const router = [
  {
    name: "Access Controls",
    key: "access_controls",
    path: "access-control",
    code: "SDM-29DE5B46",
    description: "Permissions Management",
    icon: "fa-solid fa-circle-half-stroke",
    main_menu: null,
    order: 1,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Access Rules",
    key: "access_rules",
    path: "access-rules",
    code: "SDM-5890A6FC",
    description: "Resource Access Management",
    icon: "fa-solid fa-scale-balanced",
    main_menu: null,
    order: 2,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Side Menus",
    key: "side_menu",
    path: "side-menu",
    code: "SDM-2105ABEB",
    description: "Navigation Configuration",
    icon: "fa-solid fa-list",
    main_menu: null,
    order: 3,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Roles",
    key: "roles",
    path: "roles",
    code: "SDM-7CFFF150",
    description: "User Permissions",
    icon: "fa-solid fa-user-lock",
    main_menu: null,
    order: 4,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Shifts",
    key: "shift",
    path: "shift",
    code: "SDM-CEE3C527",
    description: "Work Shift Management",
    icon: "fa-solid fa-timeline",
    main_menu: null,
    order: 5,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Avatar",
    key: "avatar",
    path: "avatar",
    code: "SDM-95E912C0",
    description: "Profile Images",
    icon: "fa-solid fa-user-tie",
    main_menu: null,
    order: 6,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Users",
    key: "user",
    path: "user",
    code: "SDM-9508BCF5",
    description: "User Management",
    icon: "fa-solid fa-user-shield",
    main_menu: null,
    order: 7,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Password Policy",
    key: "password_policy",
    path: "password-policy",
    code: "SDM-14689974",
    description: "Security Standards",
    icon: "fa-solid fa-lock",
    main_menu: null,
    order: 8,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "TimeZones",
    key: "timezone",
    path: "timezone",
    code: "SDM-C01801ED",
    description: "Time Settings",
    icon: "fa-regular fa-hourglass-half",
    main_menu: null,
    order: 9,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Device Management",
    key: "device_management",
    path: "device-management",
    code: "SDM-4721BFA4",
    description: "Device Control",
    icon: "fa-solid fa-sitemap",
    main_menu: null,
    order: 10,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Company",
    key: "company",
    path: "company",
    code: "SDM-407D34C0",
    description: "Organization Management",
    icon: "fa-regular fa-building",
    main_menu: null,
    order: 11,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Branch",
    key: "branch",
    path: "branch",
    code: "SDM-E834732B",
    description: "Business Units",
    icon: "fa-solid fa-code-branch",
    main_menu: null,
    order: 12,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Client",
    key: "client",
    path: "client",
    code: "SDM-7D7158F2",
    description: "Customer Details",
    icon: "fa-solid fa-people-group",
    main_menu: null,
    order: 13,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Vehicles",
    key: "vehicles",
    path: "vehicles",
    code: "SDM-76676B1E",
    description: "Vehicle Management",
    icon: "fa-solid fa-truck",
    main_menu: null,
    order: 14,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Bunk Details",
    key: "bunk",
    path: "bunk",
    code: "SDM-2B0D1EE9",
    description: "Fuel Station Management",
    icon: "fa-solid fa-gas-pump",
    main_menu: null,
    order: 15,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Bank Details",
    key: "bank_details",
    path: "bank-details",
    code: "SDM-C14736D8",
    description: "Financial Information",
    icon: "fa-solid fa-money-check-dollar",
    main_menu: null,
    order: 16,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Newsletter",
    key: "newsletter",
    path: "newsletter",
    code: "SDM-31C51AEE",
    description: "Information Dissemination",
    icon: "fa-regular fa-envelope",
    main_menu: null,
    order: 17,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Notification",
    key: "notification",
    path: "notification",
    code: "SDM-AD3EAA9C",
    description: "Alerts and Updates",
    icon: "fa-regular fa-bell",
    main_menu: null,
    order: 18,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Order",
    key: "order",
    path: "order",
    code: "SDM-0CAFE93A",
    description: "Order Processing",
    icon: "fa-solid fa-business-time",
    main_menu: null,
    order: 19,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: false,
    active: true,
    sub_menus: [],
  },
  {
    name: "Reports",
    key: "reports",
    path: "reports",
    code: "SDM-8F0F1BC2",
    description: "Analytics Hub",
    icon: "fa-regular fa-file-excel",
    main_menu: null,
    order: 20,
    group: [],
    type: "main_menu",
    view: true,
    create: true,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Repairs And Maintenance",
    key: "repairs_and_maintenance",
    path: "repairs-and-maintenance",
    code: "SDM-282A8F2A",
    description: "Asset Care",
    icon: "fa-solid fa-screwdriver-wrench",
    main_menu: null,
    order: 21,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Payments",
    key: "payments",
    path: "payments",
    code: "SDM-8E0950E8",
    description: "Financial Transactions",
    icon: "fa-solid fa-file-invoice-dollar",
    main_menu: null,
    order: 22,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Logs",
    key: "logs",
    path: "logs",
    code: "SDM-CBB5B2A7",
    description: "Activity Tracking",
    icon: "fa-regular fa-file-lines",
    main_menu: null,
    order: 23,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: true,
    active: true,
    sub_menus: [],
  },
  {
    name: "Help and Support",
    key: "help_and_support",
    path: "help-and-support",
    code: "SDM-0C2BA4F7",
    description: "Support Center",
    icon: "fa-solid fa-circle-info",
    main_menu: null,
    order: 24,
    group: [],
    type: "main_menu",
    view: true,
    create: false,
    update: false,
    active: true,
    sub_menus: [],
  },
];
